### ISSUE TITLE
12beta 7 installation bug

### ISSUE THREAD

**Issue by mjs520** [CloverHackyColor/CloverBootloader#450] opened 2021-09-23 09:03 UTC
When will clover fix the unlimited restart problem of 12beta 7 installation? Look forward to clover 5140 update

**Comment by SergeySlice** [comment] 2021-09-25 04:38
The problem is resolved but not committed yet. Wait please 5140.

**Comment by mjs520** [comment] 2021-09-25 22:03
Fortunately, thank you

**Closed** 2021-09-27 14:54 UTC

**Comment by alessaba** [comment] 2021-09-30 07:13
I keep having the same problem when installing beta 7 and 8. Is there some setting i need to enable?
I think i read on OpenCore you have to enable "AdviseFeatures" but there is no such option in Clover, it seems
