### ISSUE TITLE
Clover Technical Documentation

### ISSUE THREAD

**Issue by MasterCna** [CloverHackyColor/CloverBootloader#196] opened 2020-07-01 12:37 UTC
I trying to find any technical documentation about the project and how it works and this stuff. Is anyone has a recommendation or something?

**Comment by asgmeonerandom** [comment] 2020-07-01 13:31
You are reverse engineering, can't you figure out?

**Comment by DMNerd** [comment] 2020-07-02 13:06
> You are reverse engineering, can't you figure out?

Very unhelpful.

**Comment by vectorsigma72** [comment] 2020-07-02 14:27
Hi guys, I'm closing this issue as duplicate of #183 where you can find the link to the wiki.

**Closed by vectorsigma72** 2020-07-02 14:27 UTC
Labels: duplicate
